### ISSUE TITLE
Demo migrations not working

### ISSUE THREAD

**Issue by lubekpl** [FlyoverWorks/storytime#123]
Hi,

wanted to try out the demo but runing migrations on Heroku fails with the fallowing error:

```
Migrating to SetSiteLayout (20150331135784)
== 20150331135784 SetSiteLayout: migrating ====================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `set_site_layout_and_subscription_email_from' for Storytime::Migrators::V1:Module/app/db/migrate/20150331135784_set_site_layout.storytime.rb:4:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `set_site_layout_and_subscription_email_from' for Storytime::Migrators::V1:Module
/app/db/migrate/20150331135784_set_site_layout.storytime.rb:4:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by bcroesch** [comment]
@lubekpl thanks for the heads up. Just pushed a fix for this. Can you give it another shot and let me know if it's working for you now?

**Comment by lubekpl** [comment]
@bcroesch no problems with the deploy now, thanks! :-)
