### ISSUE TITLE
Posting Comment leads to 404 error 

### ISSUE THREAD

**Issue by campgurus** [FlyoverWorks/storytime#175]
When I try to make a comment on a blog post, I get the following error.  Any help appreciated.  Alternatively, is there a way to disable comments?:

2015-06-06T15:43:36.321698+00:00 app[web.1]: Completed 404 Not Found in 16ms (ActiveRecord: 10.8ms)
2015-06-06T15:43:36.301225+00:00 app[web.1]: Started POST "/news/posts/the-start-of-bowiki/comments" for 207.158.41.199 at 2015-06-06 15:43:36 +0000
2015-06-06T15:43:36.313994+00:00 app[web.1]:    (3.8ms)  SELECT COUNT(*) FROM "storytime_sites"
2015-06-06T15:43:36.320518+00:00 app[web.1]:   Storytime::Site Load (1.3ms)  SELECT  "storytime_sites".* FROM "storytime_sites"  ORDER BY "storytime_sites"."id" ASC LIMIT 1
2015-06-06T15:43:36.323316+00:00 app[web.1]:
2015-06-06T15:43:36.323320+00:00 app[web.1]: ActiveRecord::RecordNotFound (Couldn't find Storytime::Post without an ID):
2015-06-06T15:43:36.323322+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/finder_methods.rb:433:in `find_with_ids'
2015-06-06T15:43:36.323323+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/finder_methods.rb:71:in `find'
2015-06-06T15:43:36.323325+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/friendly_id-5.1.0/lib/friendly_id/finder_methods.rb:20:in `find'
2015-06-06T15:43:36.323326+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/bundler/gems/storytime-fa627344c7e2/app/controllers/storytime/comments_controller.rb:32:in `set_post'
2015-06-06T15:43:36.323328+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2015-06-06T15:43:36.323329+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:145:in `call'
2015-06-06T15:43:36.323331+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
2015-06-06T15:43:36.323332+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
2015-06-06T15:43:36.323334+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `block in call'
2015-06-06T15:43:36.323335+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `each'
2015-06-06T15:43:36.323337+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
2015-06-06T15:43:36.323338+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
2015-06-06T15:43:36.323340+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `call'
2015-06-06T15:43:36.323341+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
2015-06-06T15:43:36.323343+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/bundler/gems/storytime-fa627344c7e2/app/controllers/storytime/application_controller.rb:65:in `scope_current_site'
2015-06-06T15:43:36.323344+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2015-06-06T15:43:36.323345+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `call'
2015-06-06T15:43:36.323347+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `block in halting'
2015-06-06T15:43:36.323348+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
2015-06-06T15:43:36.323349+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
2015-06-06T15:43:36.323351+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2015-06-06T15:43:36.323352+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2015-06-06T15:43:36.323353+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
2015-06-06T15:43:36.323355+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
2015-06-06T15:43:36.323356+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2015-06-06T15:43:36.323357+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2015-06-06T15:43:36.323358+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2015-06-06T15:43:36.323360+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2015-06-06T15:43:36.323361+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
2015-06-06T15:43:36.323363+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-06-06T15:43:36.323364+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
2015-06-06T15:43:36.323365+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2015-06-06T15:43:36.323367+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2015-06-06T15:43:36.323368+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/logging.rb:107:in `process_action'
2015-06-06T15:43:36.323369+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2015-06-06T15:43:36.323370+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
2015-06-06T15:43:36.323375+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
2015-06-06T15:43:36.323377+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
2015-06-06T15:43:36.323378+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2015-06-06T15:43:36.323379+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
2015-06-06T15:43:36.323380+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
2015-06-06T15:43:36.323381+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2015-06-06T15:43:36.323382+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2015-06-06T15:43:36.323384+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-06-06T15:43:36.323385+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2015-06-06T15:43:36.323387+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-06-06T15:43:36.323389+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2015-06-06T15:43:36.323390+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2015-06-06T15:43:36.323392+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
2015-06-06T15:43:36.323393+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
2015-06-06T15:43:36.323395+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:51:in `serve'
2015-06-06T15:43:36.323396+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-06-06T15:43:36.323397+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2015-06-06T15:43:36.323399+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-06-06T15:43:36.323400+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2015-06-06T15:43:36.323401+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
2015-06-06T15:43:36.323403+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2015-06-06T15:43:36.323404+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2015-06-06T15:43:36.323406+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2015-06-06T15:43:36.323407+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
2015-06-06T15:43:36.323408+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:38:in `call'
2015-06-06T15:43:36.323410+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
2015-06-06T15:43:36.323411+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
2015-06-06T15:43:36.323412+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2015-06-06T15:43:36.323414+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
2015-06-06T15:43:36.323415+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
2015-06-06T15:43:36.323416+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
2015-06-06T15:43:36.323417+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2015-06-06T15:43:36.323418+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
2015-06-06T15:43:36.323420+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
2015-06-06T15:43:36.323421+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2015-06-06T15:43:36.323423+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
2015-06-06T15:43:36.323424+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
2015-06-06T15:43:36.323425+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
2015-06-06T15:43:36.323426+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2015-06-06T15:43:36.323427+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2015-06-06T15:43:36.323428+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2015-06-06T15:43:36.323433+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2015-06-06T15:43:36.323434+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-06-06T15:43:36.323435+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
2015-06-06T15:43:36.323437+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
2015-06-06T15:43:36.323438+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2015-06-06T15:43:36.323439+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2015-06-06T15:43:36.323441+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
2015-06-06T15:43:36.323442+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
2015-06-06T15:43:36.323443+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-06-06T15:43:36.323444+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
2015-06-06T15:43:36.323446+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
2015-06-06T15:43:36.323447+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-06-06T15:43:36.323449+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2015-06-06T15:43:36.323450+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
2015-06-06T15:43:36.323451+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2015-06-06T15:43:36.323452+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2015-06-06T15:43:36.323454+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/configuration.rb:51:in `call'
2015-06-06T15:43:36.323455+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
2015-06-06T15:43:36.323456+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
2015-06-06T15:43:36.323458+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
2015-06-06T15:43:36.323459+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
2015-06-06T15:43:36.323461+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by campgurus** [comment]
removed storytime. closing this
